#!/usr/bin/env python
import sys
import json

def shellvar(name, value):
    print("export %s='%s'" % (name, value))

tokens = json.load(sys.stdin)

shellvar("OS_TOKEN", tokens['access']['token']['id'])

for service in tokens['access']['serviceCatalog']:
    stype = service['type'].replace("-", "_").upper()
    url = service['endpoints'][0]['publicURL']
    shellvar("OS_%s_URL" % stype, url)
